name: Detect Secrets

on: [push,pull_request]

jobs:
  Detect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Detect Secrets
      uses: evanextreme/detect-secrets-actions@1.0.0
