name: gitleaks

on: [push,pull_request]

jobs:
  Detect Secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Detect Secrets
      uses: evanextreme/detect-secrets-action@1.0.0
